[phases.setup]
nixPkgs = [
    "nodejs", 
    "python311", 
    "python311Packages.pandas", 
    "python311Packages.numpy", 
    "python311Packages.flask", 
    "python311Packages.flask-cors",
    "python311Packages.python-dotenv",
    "python311Packages.requests",
    "ffmpeg", 
    "imagemagick", 
    "libglvnd",
    "glib",
    "zlib",
    "curl",
    "gcc",
    "gnumake",
    "pkg-config",
    "openssl",
    "libffi",
    "cairo",
    "pango",
    "libjpeg",
    "giflib",
    "librsvg",
    "pixman"
]

[phases.build]
cmds = []

[start]
cmd = "npm start"
